# -*- coding: utf-8 -*-
"""NASA_API_Tiago.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwh04hHsAwZmuxkzm3YhrIx1oQaqfm_j
"""





"""Nome: Tiago Castro Orbite
RA: 23011105
MAHLI
"""

import requests

r = requests.get('https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?sol=1000&camera=MAHLI&api_key=n7eHVk1JAmkVdbJxgA8py91hFxNWCA6vstKSFE9B')

r.json()

